### ISSUE TITLE
Can't connect to nexus via ssl

### ISSUE THREAD

**Issue by patrickcrocker** [clearent/nexus#3]
I've generated my keystore:
```
keytool -genkey -noprompt \
  -keyalg RSA \
  -keysize 2048 \
  -validity 365 \
  -alias nexus \
  -dname 'CN=Patrick Crocker, OU=IT, O=Somewhere, L=Dallas, ST=TX, C=US' \
  -keystore keystore.jks \
  -storepass changeit \
  -keypass changeit
```

And then launched the image:
```
docker run -d --name nexus \
  -p 8443:8443 \
  -v $PWD/keystore.jks:/nexus-data/keystore.jks \
  -e JKS_PASSWORD="changeit" \
  clearent/nexus
```

I can connect via non-ssl:
```
curl http://192.168.99.100:8081 -I
HTTP/1.1 200 OK
...
```

But ssl fails:
```
curl https://192.168.99.100:8443 -I
curl: (7) Failed to connect to 192.168.99.100 port 8443: Connection refused
```

If I connect to the running instance (and install curl) I get the same results. What is interesting is that I _can_ connect to localhost via ssl:
```
curl https://127.0.0.1:8443 -I -k
HTTP/1.1 200 OK
...
```

Any ideas?

**Comment by patrickcrocker** [comment]
Nevermind! An update of docker and a reboot later, everything is working fine.

**Comment by cavemandaveman** [comment]
Just out of curiosity, were you initially using a version of docker older than 1.10?

**Comment by patrickcrocker** [comment]
No, it was 1.11.  I'm now using the community version: Docker version
17.03.0-ce, build 60ccb22
