### ISSUE TITLE
Need extra expose PORT

### ISSUE THREAD

**Issue by DblK** [clearent/nexus#4]
Hi,

You image is great but from my point of view it's missing a EXPOSE 5000 for example.
When you use it with a docker registry, you need an extra port to connect to it.

Could you just add one and update the docs according to this issue?

Thank you

**Comment by cavemandaveman** [comment]
Thank you for the suggestion. Although it's not necessary for it to be on the expose line, since you can still route to 5000 internally with the `docker run` command, it does explicitly show that the port is available.
I went ahead and added it for clarity.
